function tau_1 = ControlTorque1(g,kd,kp,l_1,l_2,m1,m2,q_1,q_2,q_1d,q_2d,q_1r,q_1dr,q_1ddr)
%CONTROLTORQUE1
%    TAU_1 = CONTROLTORQUE1(G,KD,KP,L_1,L_2,M1,M2,Q_1,Q_2,Q_1D,Q_2D,Q_1R,Q_1DR,Q_1DDR)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Mar-2018 02:24:50

t2 = l_1.^2;
t3 = q_1d-q_1dr;
t4 = kd.*t3;
t5 = q_1-q_1r;
t6 = kp.*t5;
t7 = -q_1ddr+t4+t6;
t8 = l_2.^2;
t9 = q_1.*2.0;
t10 = q_2.*2.0;
t11 = t9+t10;
t12 = cos(t11);
t13 = q_1d.^2;
t14 = q_2+t9;
t15 = sin(t11);
t16 = q_1+q_2;
t17 = cos(t16);
t18 = l_2.*t7;
t19 = l_2.*t12.*t13;
t20 = q_2d.^2;
t21 = l_2.*t12.*t20;
t22 = sin(q_2);
t23 = cos(t14);
t24 = l_1.*t13.*t23;
t25 = cos(q_2);
t26 = l_1.*t7.*t25;
t27 = sin(t14);
t28 = l_2.*q_1d.*q_2d.*t12.*2.0;
t37 = l_2.*t15;
t29 = l_2-t37;
t30 = 1.0./t29;
t32 = g.*t17;
t33 = l_2.*t7.*t15;
t34 = l_1.*t7.*t27;
t35 = l_1.*t13.*t22;
t31 = t18+t19+t21+t24+t26+t28-t32-t33-t34-t35;
t36 = m2.^2;
t38 = l_2.*t15.*t30.*t31;
t43 = l_2.*t30.*t31;
t39 = t18+t19+t21+t24+t26+t28-t32-t33-t34-t35+t38-t43;
t40 = cos(q_1);
t41 = cos(t9);
t42 = sin(t9);
tau_1 = -m1.*t2.*t7-m2.*t2.*t7-m2.*t7.*t8+g.*l_2.*m2.*t17+g.*l_1.*m1.*t40+g.*l_1.*m2.*t40-l_2.*t8.*t36.*t39+m2.*t7.*t8.*t15-m2.*t8.*t12.*t13-m2.*t8.*t12.*t20+m1.*t2.*t7.*t42+m2.*t2.*t7.*t42-m1.*t2.*t13.*t41-m2.*t2.*t13.*t41-l_1.*l_2.*m2.*t7.*t25.*2.0+l_1.*l_2.*m2.*t7.*t27.*2.0-l_1.*l_2.*m2.*t13.*t23.*2.0-l_1.*l_2.*m2.*t20.*t22-l_1.*l_2.*m2.*t20.*t23-m2.*q_1d.*q_2d.*t8.*t12.*2.0+l_2.*t8.*t15.*t36.*t39-l_1.*t8.*t25.*t36.*t39+l_1.*t8.*t27.*t36.*t39-l_1.*l_2.*m2.*q_1d.*q_2d.*t22.*2.0-l_1.*l_2.*m2.*q_1d.*q_2d.*t23.*2.0;
