function tau_1 = ControlTorque1(g,kd,kp,l_1,l_2,m1,m2,q_1,q_2,q_1d,q_2d,q_1dd)
%CONTROLTORQUE1
%    TAU_1 = CONTROLTORQUE1(G,KD,KP,L_1,L_2,M1,M2,Q_1,Q_2,Q_1D,Q_2D,Q_1DD)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    19-Mar-2018 15:47:35

t2 = l_1.^2;
t3 = kd.*q_1d;
t4 = q_1-q_1d;
t5 = kp.*t4;
t6 = -q_1dd+t3+t5;
t7 = l_2.^2;
t8 = q_1.*2.0;
t9 = q_2.*2.0;
t10 = t8+t9;
t11 = cos(t10);
t12 = sin(t10);
t13 = q_1+q_2;
t14 = cos(t13);
t15 = l_2.*t6;
t16 = q_1d.^2;
t17 = l_2.*t11.*t16;
t18 = q_2d.^2;
t19 = l_2.*t11.*t18;
t20 = q_2+t8;
t21 = cos(q_2);
t22 = l_1.*t6.*t21;
t23 = sin(q_2);
t24 = cos(t20);
t25 = l_1.*t16.*t24;
t26 = sin(t20);
t27 = l_2.*q_1d.*q_2d.*t11.*2.0;
t36 = l_2.*t12;
t28 = l_2-t36;
t29 = 1.0./t28;
t31 = g.*t14;
t32 = l_2.*t6.*t12;
t33 = l_1.*t6.*t26;
t34 = l_1.*t16.*t23;
t30 = t15+t17+t19+t22+t25+t27-t31-t32-t33-t34;
t35 = m2.^2;
t37 = l_2.*t12.*t29.*t30;
t42 = l_2.*t29.*t30;
t38 = t15+t17+t19+t22+t25+t27-t31-t32-t33-t34+t37-t42;
t39 = cos(q_1);
t40 = cos(t8);
t41 = sin(t8);
tau_1 = -m1.*t2.*t6-m2.*t2.*t6-m2.*t6.*t7+g.*l_2.*m2.*t14+g.*l_1.*m1.*t39+g.*l_1.*m2.*t39-l_2.*t7.*t35.*t38+m2.*t6.*t7.*t12-m2.*t7.*t11.*t16-m2.*t7.*t11.*t18+m1.*t2.*t6.*t41+m2.*t2.*t6.*t41-m1.*t2.*t16.*t40-m2.*t2.*t16.*t40-l_1.*l_2.*m2.*t6.*t21.*2.0+l_1.*l_2.*m2.*t6.*t26.*2.0-l_1.*l_2.*m2.*t16.*t24.*2.0-l_1.*l_2.*m2.*t18.*t23-l_1.*l_2.*m2.*t18.*t24-m2.*q_1d.*q_2d.*t7.*t11.*2.0+l_2.*t7.*t12.*t35.*t38-l_1.*t7.*t21.*t35.*t38+l_1.*t7.*t26.*t35.*t38-l_1.*l_2.*m2.*q_1d.*q_2d.*t23.*2.0-l_1.*l_2.*m2.*q_1d.*q_2d.*t24.*2.0;
