function tau_1 = ControlTorque1(g,kd,kp,l_1,l_2,m1,m2,q_1,q_2,q_1d,q_2d,q_2dd)
%CONTROLTORQUE1
%    TAU_1 = CONTROLTORQUE1(G,KD,KP,L_1,L_2,M1,M2,Q_1,Q_2,Q_1D,Q_2D,Q_2DD)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    09-Mar-2018 18:25:29

t2 = l_1.^2;
t3 = kd.*q_1d;
t4 = q_1-q_1d;
t5 = kp.*t4;
t6 = t3+t5;
t7 = l_2.^2;
t8 = cos(q_1);
t9 = q_1.*2.0;
t10 = q_2.*2.0;
t11 = t9+t10;
t12 = sin(t11);
t13 = q_1d.^2;
t14 = cos(t9);
t15 = cos(t11);
t16 = sin(t9);
t17 = q_2d.^2;
t18 = q_2+t9;
t19 = cos(t18);
t20 = sin(t18);
t21 = cos(q_2);
t22 = sin(q_2);
tau_1 = m2.*q_2dd.*t7-m1.*t2.*t6-m2.*t2.*t6-m2.*t6.*t7+g.*l_1.*m1.*t8+g.*l_1.*m2.*t8-m2.*q_2dd.*t7.*t12+m1.*t2.*t6.*t16+m2.*t2.*t6.*t16+m2.*t6.*t7.*t12-m1.*t2.*t13.*t14-m2.*t2.*t13.*t14-m2.*t7.*t13.*t15-m2.*t7.*t15.*t17+g.*l_2.*m2.*cos(q_1+q_2)-l_1.*l_2.*m2.*q_2dd.*t20+l_1.*l_2.*m2.*q_2dd.*t21+l_1.*l_2.*m2.*t6.*t20.*2.0-l_1.*l_2.*m2.*t6.*t21.*2.0-l_1.*l_2.*m2.*t13.*t19.*2.0-l_1.*l_2.*m2.*t17.*t19-l_1.*l_2.*m2.*t17.*t22-m2.*q_1d.*q_2d.*t7.*t15.*2.0-l_1.*l_2.*m2.*q_1d.*q_2d.*t19.*2.0-l_1.*l_2.*m2.*q_1d.*q_2d.*t22.*2.0;
