function L = Lagrange(g,l_1,l_2,m1,m2,q_1,q_2,q_1d,q_2d)
%LAGRANGE
%    L = LAGRANGE(G,L_1,L_2,M1,M2,Q_1,Q_2,Q_1D,Q_2D)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    09-Mar-2018 18:25:29

t2 = q_1+q_2;
t3 = cos(t2);
t4 = sin(t2);
t6 = cos(q_1);
t7 = sin(q_1);
t9 = l_2.*t4;
t10 = l_1.*t7;
t11 = t9+t10;
t5 = -q_1d.*t11+q_1d.*(l_2.*t3+l_1.*t6)+l_2.*q_2d.*t3-l_2.*q_2d.*t4;
t8 = l_1.*q_1d.*t6-l_1.*q_1d.*t7;
L = m2.*t5.^2.*(1.0./2.0)+m1.*t8.^2.*(1.0./2.0)-g.*m2.*t11-g.*l_1.*m1.*t7;
